import Foundation

// MARK: - Presentation content
//
// The slide content contract between the content generator (a Hermes turn),
// the designers (PDF + PPTX) and the on-disk deck record. The model answers
// with one JSON object; `SlideContent.parse` decodes it tolerantly (models
// wrap JSON in prose or ```json fences — the parser grabs the outermost
// {...} object and ignores the rest).

/// The tone of a deck: how formal, how dense, who it is for.
enum PresentationTone: String, CaseIterable, Codable, Identifiable {
    case academic
    case business
    case casual

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .academic: return "Academic"
        case .business: return "Business"
        case .casual: return "Casual"
        }
    }

    /// Instruction given to the content model, so the tone lands in wording
    /// and density rather than staying a label.
    var contentGuidance: String {
        switch self {
        case .academic:
            return "Academic register: precise, evidence-forward, comfortable with terminology. Aim for one idea per bullet, 3-5 bullets per slide."
        case .business:
            return "Business register: decisive, structured, outcome-oriented. Short punchy bullets (under 10 words each), 3-5 per slide."
        case .casual:
            return "Casual register: friendly, concrete, jargon-light. Short bullets a classmate would actually read, 3-5 per slide."
        }
    }
}

/// One slide's worth of content.
struct Slide: Codable, Equatable, Sendable {
    var title: String
    var bullets: [String]
    /// Detailed speaker notes for this slide (what to say, how long).
    var notes: String
    /// A short noun phrase used to find a relevant image (e.g. "atom model").
    /// Empty → the slide gets a design-only treatment.
    var imageQuery: String = ""
}

/// The full deck as generated by the content turn.
struct SlideContent: Codable, Equatable, Sendable {
    var title: String
    var subtitle: String
    var slides: [Slide]

    /// How the deck's time budget maps to slide count (~1-2 min per slide).
    /// Used when the request gives a presentation length in minutes instead
    /// of a slide count.
    static func slideCount(forMinutes minutes: Int) -> Int {
        max(5, min(20, Int((Double(minutes) / 1.5).rounded())))
    }

    static func parse(_ text: String) -> SlideContent? {
        guard let start = text.firstIndex(of: "{"),
              let end = text.lastIndex(of: "}"),
              start < end else { return nil }
        let jsonText = String(text[start...end])
        guard let data = jsonText.data(using: .utf8),
              let content = try? JSONDecoder().decode(SlideContent.self, from: data)
        else { return nil }
        let title = content.title.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !title.isEmpty, !content.slides.isEmpty else { return nil }
        let slides = content.slides.compactMap { slide -> Slide? in
            let t = slide.title.trimmingCharacters(in: .whitespacesAndNewlines)
            let bullets = slide.bullets
                .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
                .filter { !$0.isEmpty }
            guard !t.isEmpty, !bullets.isEmpty else { return nil }
            return Slide(
                title: t,
                bullets: bullets,
                notes: slide.notes.trimmingCharacters(in: .whitespacesAndNewlines),
                imageQuery: slide.imageQuery.trimmingCharacters(in: .whitespacesAndNewlines))
        }
        guard !slides.isEmpty else { return nil }
        return SlideContent(
            title: title,
            subtitle: content.subtitle.trimmingCharacters(in: .whitespacesAndNewlines),
            slides: slides)
    }
}

// MARK: - Content generator

/// Produces the slide content for a deck: one bounded Hermes turn on the
/// skill's own session (never the bar's), answered as a single JSON object.
/// The turn both researches and writes — the model has web_search and its
/// other tools, so the deck is grounded in real material, not invented.
///
/// The skill's session is long-lived (see PresentationGeneratorSkill), so the
/// expensive Hermes spawn happens once, not per deck.
struct SlideContentGenerator {

    /// Build the content-turn prompt. `styleName` is the resolved design style
    /// (only its *name* — the model doesn't need the palette, just the vibe).
    static func prompt(topic: String, slideCount: Int, tone: PresentationTone,
                       styleName: String, includeNotes: Bool, subtitleHint: String) -> String {
        let notesInstruction: String
        if includeNotes {
            notesInstruction = """
                - "notes": detailed speaker notes for that slide — what to say, \
                the key point to land, and roughly how long (e.g. "Spend ~90s: \
                walk through the Schrödinger equation and why the wavefunction \
                is complex."). Specific and actionable, never generic.
                """
        } else {
            notesInstruction = """
                - "notes": a one-line summary of the slide's takeaway (used \
                for internal structure; the user didn't ask for full notes).
                """
        }
        return """
        Create a complete presentation deck on: \(topic)

        Requirements:
        - Exactly \(slideCount) slides. Slide 1 is the title slide (its "title" \
        is the deck title and its "bullets" are empty). The rest: intro → key \
        concepts → examples → conclusion, in a sensible order for the topic.
        - \(tone.contentGuidance)
        - Design vibe: \(styleName). Keep bullet text concise — a wall of text \
        is a failed slide.
        - Ground the content in real, current material: use web search for \
        anything factual, and prefer specific numbers, names and dates over \
        vague claims. Never invent facts.

        Answer ONLY with a JSON object — no prose, no code fences:
        {
          "title": "Deck title",
          "subtitle": "One-line subtitle (course, audience, or date)\(subtitleHint)",
          "slides": [
            {
              "title": "Slide title",
              "bullets": ["bullet one", "bullet two", "bullet three"],
              "notes": "speaker notes for this slide",
              "imageQuery": "short noun phrase for a relevant image (empty if none)"
            }
          ]
        }

        Per-slide rules:
        - "bullets": 3-5 concise bullets for content slides; empty for the title slide.
        - "imageQuery": a 2-4 word noun phrase a search engine could find an \
        image for (e.g. "double slit experiment diagram"). Use it on 3-6 slides \
        where a visual genuinely helps; empty string elsewhere. Never invent an \
        image for something unvisual (equations, abstract claims) — empty is better.
        \(notesInstruction)
        """
    }

    /// Run the content turn and decode the deck. Throws a readable error on
    /// model failure or unparseable output, so the caller can fail honestly.
    static func generate(session: HermesSession, topic: String, slideCount: Int,
                         tone: PresentationTone, styleName: String,
                         includeNotes: Bool, subtitleHint: String = "") async throws -> SlideContent {
        let prompt = Self.prompt(
            topic: topic, slideCount: slideCount, tone: tone,
            styleName: styleName, includeNotes: includeNotes,
            subtitleHint: subtitleHint)
        var transcript = ""
        for await event in await session.prompt(prompt, capture: false) {
            switch event {
            case .text(let chunk): transcript += chunk
            case .failed(let message):
                throw PresentationError.modelFailed(message)
            case .thought, .toolStarted, .toolProgress, .usage, .finished:
                break
            }
        }
        guard let content = SlideContent.parse(transcript) else {
            throw PresentationError.unparseableContent(transcript)
        }
        return content
    }
}

// MARK: - Errors

enum PresentationError: LocalizedError {
    case modelFailed(String)
    case unparseableContent(String)
    case invalidRequest(String)
    case notFound(String)
    case exportFailed(String)

    var errorDescription: String? {
        switch self {
        case .modelFailed(let m): return "The content model failed: \(m)"
        case .unparseableContent(let t):
            let preview = String(t.prefix(300))
            return "The model's reply didn't decode as a deck. Reply started: \(preview)"
        case .invalidRequest(let m): return m
        case .notFound(let m): return m
        case .exportFailed(let m): return m
        }
    }
}
