import Foundation

/// Writes Alfred's persona and owner profile into the files Hermes reads.
///
/// Hermes loads two files from `$HERMES_HOME` and injects them into different
/// halves of its system prompt:
///
///   * `SOUL.md`  — identity. Goes in the *stable* half (agent/prompt_builder.py
///                  `load_soul_identity`), so it should describe who Alfred is
///                  and how it behaves, and should not contain anything that
///                  changes turn to turn.
///   * `USER.md`  — owner profile. Goes in the *volatile* half
///                  (agent/agent_init.py), refreshed per turn.
///
/// Without this, Alfred runs on Hermes' stock Nous Research persona — a generic
/// assistant with no knowledge of its owner, which is the opposite of the point.
///
/// # Egress
///
/// Everything written here is sent to the model provider on **every turn**. That
/// makes file contents an egress decision, not a formatting one. Owner facts are
/// therefore taken from `PersonaTemplate.ownerBlock`, which renders only what the
/// owner themselves configured, rather than from raw memory or screen captures.
/// `CloudProjection`'s registry is the authority on what may leave the Mac; this
/// exporter deliberately adds no new source of owner data beyond it.
///
/// # Not clobbering hand edits
///
/// The user may write their own SOUL.md — Hermes documents it as theirs to edit.
/// Files are only overwritten when they are absent, still Hermes' stock default,
/// or carry this exporter's marker. Anything else is left alone and reported.
enum PersonaExporter {

    /// Marks a file as generated by Alfred, so a later run may safely replace it.
    private static let marker = "<!-- generated-by: alfred -->"

    /// Hermes' shipped SOUL.md opens with this. Recognising it lets a first run
    /// replace the stock persona without treating it as a user's own writing.
    private static let stockPrefix = "You are Hermes Agent"

    enum Outcome {
        case written(URL)
        case unchanged(URL)
        /// Left alone because the user appears to have written it themselves.
        case skippedUserAuthored(URL)
        case failed(URL, Error)
    }

    // MARK: - Entry point

    /// Regenerate both files. Safe to call on every launch; writes only on change.
    @discardableResult
    static func export(snapshot: OwnerConfigSnapshot?,
                       styleProfile: WritingProfile?,
                       hermesHome: URL = defaultHermesHome) -> [Outcome] {
        let style = styleDescription(styleProfile)
        return [
            write(soulDocument(snapshot: snapshot, styleContext: style),
                  to: hermesHome.appendingPathComponent("SOUL.md")),
            write(userDocument(snapshot: snapshot, styleContext: style),
                  to: hermesHome.appendingPathComponent("USER.md")),
        ]
    }

    /// Describe how the owner writes using **only aggregate statistics**.
    ///
    /// Deliberately NOT `WritingStyleStore.generateStyleContext()`. That renders
    /// `commonGreetings`, `commonClosings` and `commonPhrases` — verbatim excerpts
    /// mined from the owner's sent messages. On the local path that is fine, but
    /// this file is uploaded to the model provider on every single turn, and the
    /// profile here is built from 1000+ imported personal messages: the first
    /// version of this exporter shipped literal openers like "Hi Baby" and
    /// "Good Morning My" to the cloud.
    ///
    /// Averages, a formality score and an emoji rate convey the same "write short,
    /// casual, with emoji" instruction without transmitting anything the owner
    /// actually wrote. If literal exemplars are ever wanted for drafting, they
    /// belong in a per-request payload the owner can see — not in a standing file
    /// attached to every unrelated query.
    private static func styleDescription(_ p: WritingProfile?) -> String? {
        guard let p, p.totalSamples > 0 else { return nil }

        let sentences: String
        switch p.avgSentenceLength {
        case ..<10: sentences = "very concise"
        case ..<15: sentences = "concise"
        case ..<22: sentences = "moderate-length"
        default:    sentences = "long"
        }

        let formality: String
        switch p.formalityScore {
        case ..<0.33: formality = "casual"
        case ..<0.66: formality = "neutral"
        default:      formality = "formal"
        }

        let emoji: String
        switch p.emojiUsage {
        case 0.5...:  emoji = "uses emoji freely"
        case 0.1..<0.5: emoji = "uses emoji occasionally"
        default:      emoji = "rarely uses emoji"
        }

        return """
            - \(sentences) sentences, averaging \(Int(p.avgSentenceLength.rounded())) words
            - paragraphs averaging \(String(format: "%.1f", p.avgParagraphLength)) sentences
            - \(formality) tone
            - \(emoji)
            """
    }

    /// `$HERMES_HOME`, else `~/.hermes` — matching hermes_constants.get_hermes_home().
    static var defaultHermesHome: URL {
        if let override = ProcessInfo.processInfo.environment["HERMES_HOME"], !override.isEmpty {
            return URL(fileURLWithPath: (override as NSString).expandingTildeInPath)
        }
        return URL(fileURLWithPath: NSHomeDirectory()).appendingPathComponent(".hermes")
    }

    // MARK: - SOUL.md

    /// Alfred's identity and behaviour. Stable across turns.
    ///
    /// Built from `PersonaTemplate.invariantInstructions` — the code-controlled
    /// guarantees Alfred already had before Hermes — rather than newly authored
    /// text, so the bar and any other surface describe the same assistant.
    ///
    /// The date is deliberately omitted: `invariantInstructions` normally appends
    /// "current date and time", which is correct for a prompt rendered per turn
    /// but wrong for a file written once. Hermes supplies the date itself, and a
    /// baked-in one would silently go stale.
    private static func soulDocument(snapshot: OwnerConfigSnapshot?, styleContext: String?) -> String {
        var parts: [String] = [marker, ""]
        // currentDate is supplied then stripped — see stripTrailingDateLine.
        parts.append(stripTrailingDateLine(PersonaTemplate.invariantInstructions(currentDate: "")))

        // How the owner writes — so drafting on their behalf sounds like them.
        // Scoped explicitly: this describes THEIR voice, not Alfred's own register,
        // and the two are frequently opposite (a user who writes casually with
        // emoji does not necessarily want a chatty assistant).
        if let styleContext, !styleContext.trimmed.isEmpty {
            parts.append("""

                WHEN DRAFTING AS THEM — messages, emails, replies you compose on \
                their behalf should match the owner's own writing style below. This \
                describes THEIR voice, not yours: do not adopt it for your own \
                replies to them.

                \(styleContext.trimmed)
                """)
        }

        return parts.joined(separator: "\n") + "\n"
    }

    /// `invariantInstructions` has no date-free variant, so the trailing line it
    /// appends is removed here rather than duplicating the template.
    private static func stripTrailingDateLine(_ text: String) -> String {
        text
            .components(separatedBy: "\n")
            .filter { !$0.trimmed.hasPrefix("Current date and time") }
            .joined(separator: "\n")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: - USER.md

    /// Facts about the owner, from their own configuration only.
    private static func userDocument(snapshot: OwnerConfigSnapshot?, styleContext: String?) -> String {
        var parts: [String] = [marker, ""]

        let ownerBlock = snapshot.map { PersonaTemplate.ownerBlock($0) } ?? ""
        if ownerBlock.trimmed.isEmpty {
            // An unconfigured install produces guidance, not placeholders. Writing
            // "REQUIRES_USER_INPUT"-style filler into a live prompt would have the
            // model reason about template scaffolding as if it were fact.
            parts.append("""
                The owner has not filled in their profile yet, so you know little \
                about them beyond this conversation. Do not guess or invent details \
                about who they are, what they do, or what they prefer. If something \
                about them would change your answer, ask.
                """)
        } else {
            parts.append(ownerBlock)
        }

        return parts.joined(separator: "\n") + "\n"
    }

    // MARK: - Writing

    private static func write(_ contents: String, to url: URL) -> Outcome {
        let fm = FileManager.default
        do {
            try fm.createDirectory(at: url.deletingLastPathComponent(),
                                   withIntermediateDirectories: true)

            if let existing = try? String(contentsOf: url, encoding: .utf8) {
                if existing == contents { return .unchanged(url) }

                let ours = existing.contains(marker)
                let stock = existing.trimmed.hasPrefix(stockPrefix)
                guard ours || stock || existing.trimmed.isEmpty else {
                    return .skippedUserAuthored(url)
                }
            }

            try contents.write(to: url, atomically: true, encoding: .utf8)
            return .written(url)
        } catch {
            return .failed(url, error)
        }
    }
}
